name: Actions WorkflowW

on: [push]

jobs:
  run-github-actions:
    runs-on: windows-latest
    steps:
      - name: List Filesssss
        run: |
              pwd 
              echo $GITHUB_SHA
              echo $GITHUB_REPOSITORY
              echo $GITHUB_WORKSPACE
               
              
      - name: Simpe JS Actionnnn
        id:   greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Snehaa
      - name: Log Greeting Timeee
        run: echo "${{steps.greet.outputs.time}}" 
