name: Actions Workflow

on:
  repository_dispatch:
    types: [build]
jobs: 
    Simple_schedule:
      runs-on: windows-latest
           
      steps:
        - name: echo a string
          run: echo "Hello"
        - name: payload
          run: echo ${{github.event.client_payload.env}}
        - name: multiline script
          run: |
            ls
            node -v
            
      