name: Filtering Workflow

on:
  push:
    branches:
      - develop
      
jobs: 
    Simple_schedule:
      runs-on: windows-latest
           
      steps:
        - name: echo a string
          run: echo "Hello"
        - name: payload
          run: echo ${{ github.event.client_payload.env }}
        - name: multiline script
          run: |
            ls
            node -v
            
      